import { useEffect } from "react";
import { useStore } from "../store";
import { MATCH_STATE_KEY } from "../../global/consts";

export const useLoadBookmarks = () => {
  const loadBookmarkTree = useStore((state) => state.loadBookmarkTree);
  const loadFetchConfig = useStore((state) => state.loadFetchConfig);
  const loadMatchState = useStore((state) => state.loadMatchState);
  const setLoadingBookmarks = useStore((state) => state.setLoadingBookmarks);
  const getSetting = useStore((state) => state.getSetting);

  useEffect(() => {
    const initialize = async () => {
      const hasItems = useStore.getState().matchedBookmarks.length > 0;
      if (!hasItems) {
        setLoadingBookmarks(true);
      }
      try {
        // Parallelize: load settings, bookmark tree, fetch config config concurrently
        // Loading settings is important to restore last selected folder and expanded state
        await Promise.all([getSetting(), loadBookmarkTree(), loadFetchConfig()]);
        // Match state depends on bookmarkTree being loaded
        await loadMatchState();
      } finally {
        setLoadingBookmarks(false);
      }
    };

    initialize();

    // Listen for state changes generated by the background script
    const handleStorageChange = (changes: any, areaName: string) => {
      if (areaName === "local" && changes[MATCH_STATE_KEY]) {
        loadMatchState();
      }
    };

    browser.storage.onChanged.addListener(handleStorageChange);
    return () => browser.storage.onChanged.removeListener(handleStorageChange);
  }, [loadBookmarkTree, loadFetchConfig, getSetting, loadMatchState, setLoadingBookmarks]);
};
